### ISSUE TITLE
Output file wrap problem

### ISSUE THREAD

**Issue by liyuanmeng** [dEajL3kA/tee-win32#1]
In Windows, using plink to execute the return of linux command, the line feed generated in the output file is not standard "/r/n", can this problem be solved?

**Comment by dEajL3kA** [comment]
I don't know how **`tee`** is involved here?

Note that *this* implementation of `tee` is totally agnostic to line endings! It just reads characters (bytes) from the 
`stdin` stream, writes them into the specified file(s), and also writes them back to the `stdout` stream. Line endings (i.e. characters `\r` and `\n`) are **not** handled specially. And they are **not** converted from Unix to DOS/Windows format, or vice versa.

Maybe have a look at:
https://en.wikipedia.org/wiki/Unix2dos

**Comment by liyuanmeng** [comment]
Thank you very much for your reply, I'll try converting "/r" to "/n" when I write to the file.

**Comment by liyuanmeng** [comment]
This program does not work on the command line with the command "more".

**Comment by liyuanmeng** [comment]
This program does not work on the command line with the command "more".

**Comment by dEajL3kA** [comment]
> This program does not work on the command line with the command "more".

Don't know. As said before, _this_ **`tee`** implementation just passes through the characters (bytes) that it reads from `stdin` to the `stdout`. It doesn't really care what its `stdout` is connected to – may it be the terminal or another program (e.g. `more`).

Anyways, seems to work for me "as expected":

![grafik](https://github.com/dEajL3kA/tee-win32/assets/13333150/5567cf73-f303-44df-9268-e156edb22862)

**Comment by liyuanmeng** [comment]
![image](https://github.com/dEajL3kA/tee-win32/assets/11526187/369f8d8b-110d-437a-9f06-6833591b1b5a)

**Comment by dEajL3kA** [comment]
`more` only stops at the end of a "page", so with just two lines it won't do anything.

Furthermore, `more` needs to be the **last** command in the chain! Otherwise it doesn't make much sense...

Try like this:
![grafik](https://github.com/dEajL3kA/tee-win32/assets/13333150/3edea014-552a-4af4-ad57-8f0efc435c90)

**Comment by liyuanmeng** [comment]
The idea is to use the "tee" as a logging tool. So all the output needs to be logged to a file. Thanks again for your reply :D

**Comment by dEajL3kA** [comment]
Yes, that should be possible. But you have to be aware that **`tee`** does nothing but reading bytes (characters) from its `stdin`, and writing them back to its `stdout`, while also dumping them into the specified file. And `tee` does **not** care where those bytes go afterwards, i.e. what is connected to the `stdout` of the `tee` process – might  be the terminal, might be another command.

The purpose of **`more`** is ***pagination***, i.e. its purpose is to show one "page" (screen) of lines at a time. Here "page" is defined by the number of lines that fit into the terminal (screen) at once. This means that `more` should be the **last** command in your chain, so that the `stdout` of the `more` process goes straight to the terminal. Anything else doesn't really make sense to me...

https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/more
